name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build and deploy gh-pages
    env:
      commit_secret: ${{secrets.COMMIT_SECRET}}
      USER_NAME   : BoisonChang
      USER_EMAIL  : dragoncres@gmail.com
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '10.15.1'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Yarn Install
        run: yarn

      - name: deploy
        run: |
          rm -rf node_modules/.cache
          yarn build
          yarn export
          touch out/.nojekyll
          cd ./out
          git init
          git config --global user.email tony14256@gmail.com
          git config --global user.name tony14256
          git status
          git remote add origin https://${{secrets.COMMIT_SECRET}}@github.com/[username]/[repo-name].git
          git checkout -b gh-pages
          git add --all
          git commit -m "Deploy Next.js to gh-pages" 
          git push origin gh-pages -f
          echo 🤘 deploy gh-pages complete.
